packages:
  - "apps/*"
  - "packages/*"

ignoredBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"

publicHoistPattern:
  - "@prisma/client"
  - "@prisma/adapter-pg"
  - pg
  - pg-pool
  - eslint
  - prettier

